### ISSUE TITLE
[BUG] GoSelect Styles

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#193]
**Describe the bug**
The `ng-select` styles included in the `go-select` styles are not shipped correctly when packaged

**Comment by grahamhency** [comment]
I'm not sure this is _actually_ an issue. This needs reproduced.

**Comment by eligolding** [comment]
I can confirm this is an issue. The problem is that we are [importing the styles from a css file](https://github.com/mobi/goponents/blob/46eab7203700a3c03a67800dcc67510be112ba1f/projects/go-lib/src/lib/components/go-select/go-select.component.scss#L3) from with a scss file, which [is not standard behavior](https://github.com/sass/node-sass/issues/2362), so the styles are just disappearing into the ether.

The fix is simply to use [the scss files](https://github.com/ng-select/ng-select/blob/44164228c533cf5a054014f9bf70421e1dccc7a2/src/ng-select/themes/default.theme.scss) that ng-select is so kind as to ship.

**Comment by grahamhency** [comment]
Closed with #341
