### ISSUE TITLE
[BUG]  Datepicker: no sync between selected date and displayed date

### ISSUE THREAD

**Issue by Ashygoyal** [mobi/goponents#277]
**Description**
There is no sync between the date selected in the datepicker and the date displayed in the i nput field. Also, on first opening the datepicker, it should ideally show the current/ present date already selected but it shows a different month, date, year.
Note: This behaviour is noticed when the timezone in the machine is default (set to IST=> UTC: 5:30). If timezone is changed to EST, datepicker works fine.

**To Reproduce**
1. Set system timezone to IST
2. Open datepicker. The Month and year on top of the datepicker wont be the current ones.
3. Select any date in datepicker, check the input field. Dates will be different.

**Expected behavior**
Datepicker must work the same, irrespective of the locales/ timezones/ OS language, etc.

**Screenshots**
For further details, please access the screencast at this link: https://tangoe-my.sharepoint.com/:v:/p/ashish_goyal/Ef3jHXFyGFtLgNES10HEV-sBIN05ToCAmopt_0Zv45EhZQ?e=eVhSnb

**Comment by patryk0605** [comment]
@grahamhency changing all `timeZone` values from `utc` to `Intl.DateTimeFormat().resolvedOptions().timeZone` in `projects/go-lib/src/lib/components/go-datepicker/date-adapter.ts` would fix this issue. 

Not sure what implications this would have on the behavior of the date picker itself which is why I posted findings here so we can discuss it. Dealing with time gives me too much of a headache 😃
