### ISSUE TITLE
[Chore] Modal Design Adjustments

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#313]
### What general chore or task would you like to see performed?
The modal is in need of some design improvements.

###### Example 
<img width="838" alt="Screen Shot 2019-11-07 at 2 12 36 PM" src="https://user-images.githubusercontent.com/11966331/68419808-f2cd7880-0168-11ea-82dd-fea72432cf56.png">

### Are there any specific steps you would like completed?
- [ ] Ensure the title and `x` to close are spaced appropriately per the design
- [ ] Currently, there is a max-width on the modal. It should be increased.

**Comment by patryk0605** [comment]
@grahamhency I'll take the issue

**Comment by Fagiolia1** [comment]
The expanded modal should have a width of 800px.

**Comment by patryk0605** [comment]
Modal specs: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d6ecbaf4ed8142b75ae33f3

**Comment by Fagiolia1** [comment]
Normal modals should have a min-width of 500px. The XL Modal should have a min-width/max-width of 800px.

**Comment by patryk0605** [comment]
@grahamhency as a FYI, this issue became more of a "Feature" instead of a "Chore" after sitting down with @Fagiolia1 to understand the requirements. I noted the PR as such. The real ask from this issue was to support a title for the modal and also standardize the size of the modal to lg (default) and xl.

**Comment by grahamhency** [comment]
Closed with #333 and #344
