### ISSUE TITLE
[Chore] Update Neutral Colors

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#323]
### What general chore or task would you like to see performed?
Please update neutral colors to the following found in the DSM:

Neutral: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/colors/5cd2a47377b0f2fc67690cf2

**Comment by grahamhency** [comment]
@kpmurphh, I believe utility colors are already being addressed in this issue. Can you confirm? #249

**Comment by kpmurphh** [comment]
yes! sorry i didn't see that (or your comment).

**Comment by grahamhency** [comment]
For clarification, we have these colors already in Goponents. This is around usage of these colors defined in the DSM.

**Comment by Ashygoyal** [comment]
@grahamhency : Whats the exact requirement here? As you mentioned, I can see the **_specific color_** is already present. 
Is this issue stating that **_it_** is not getting used properly as per DSM guidelines?

**Comment by grahamhency** [comment]
@Ashygoyal yeah, I believe that is the case. We might need to audit this against the DSM to seen what needs to change exactly.

**Comment by grahamhency** [comment]
Thanks for going through these @Ashygoyal.

> 1. Under Meteor: What exactly is a link in top navigation? Where can I find this?

I don't think we actually have any top nav links. I think this refers to links that would exist in the `go-header` (other than icons). Unless maybe they're referring to the links within a `go-action-sheet`, maybe @kpmurphh can clear this up?

> 2. Under Crater: We dont have this in goponents.

We will probably need to add this color then, and change it for the app drawer background.

> 3. Under Asteroid: Where can I find a top navigation example in goponents? We are using different colors for 'disabled text color' and 'text placeholder color'.

For the first part of this question, let's see what @kpmurphh has to say. We will need to update the colors for disabled form element text (and verify placeholder is the same) as well as the search placeholder.

> 4. Under Satellite: What is a Form Hint? Is it the left border before the hint text?

Yes, that component is `go-hint`.

> 5. Under Telescope: We don't have a shell dropdown menu border color and no hover color for tables. Where are we using Shell icons in goponents? We are using a different hex for 'search border color' and 'hover for dropdown menus'.

I think the "shell dropdown menu" is referring to `go-action-sheet`s that are rendered in the `go-header`. I would caution against changing this because it would affect all `go-action-sheet`s. @kpmurphh can we remove that requirement so that we don't affect all `go-action-sheet`s?

"Shell icons" are referring to `go-icon`s or `go-icon-button`s that appear anywhere in the `go-layout`, `go-header`, or `go-side-nav`.

We will need to update the hex's for "search border color", but changing "hover for dropdown" will affect other `go-action-sheet`s.. do we want to do this @kpmurphh??

> 6. Under Shuttle: Side Navigation Dropdown Background is not White (#FFFFFF), so probably a mistake in DSM docs.

I think it probably is, maybe @kpmurphh could update that for us?

**Comment by Ashygoyal** [comment]
@kpmurphh : gentle reminder!

**Comment by kpmurphh** [comment]
Hey @Ashygoyal,

1. The top navigation links refer to the action sheet links.
2. What Graham said.
3. This was referring to the disabled placeholder color in a form input. The “search icon and text placeholder” is referring to the global search bar in the shell as well as the search bar in tables.
4. Yes, this refers to both the color of the bar in the form hint. 
5. Yes we can remove this requirement. As for the hover colors, you can disregard the hover colors for icons and tables in question because the hover and select colors are no longer #F0F0F0 but instead darkened colors of #FFFFFF.
6. Yes this was a mistake.
 
Let me know if you have any questions.
