### ISSUE TITLE
Goponents [Version - 1.3.1] ERROR TypeError: Cannot read property 'length' of undefined     at GoSideNavService.createNavMap

### ISSUE THREAD

**Issue by chiranjeevi-tangoe** [mobi/goponents#358]
Goponents [Version - 1.3.1] ERROR TypeError: Cannot read property 'length' of undefined     at GoSideNavService.createNavMap.

![image](https://user-images.githubusercontent.com/57486898/70506631-cb474280-1b50-11ea-99f8-3491f7980bd5.png)

**Comment by StevenUlmer** [comment]
@chiranjeevi-tangoe I believe this is happening because you're initializing the side nav without any menu items or before the menu items are loaded. We can fix this and give you a better error, but really a sidenav shouldn't be initialized without menu items. If it's a problem with the menu items getting loaded after the sidenav is initialized, I would suggest looking into delaying the page from loading until you have that data as I would imagine a user would expect the navigation items to be loaded before they see a view.

**Comment by grahamhency** [comment]
Hey @chiranjeevi-tangoe, @StevenUlmer is correct on this. 

@StevenUlmer will create a PR so that we provide a better error when this happens, but this is an issue on implementation and not in Goponents.

Furthermore, because this issue was not created using the proper "Bug" template I will be closing this issue.

I would encourage you to look into using a Resolver to fetch the data before loading the layout route so that `menuItems` is defined when the component is generated. If you need assistance with that, https://angular.io/api/router/Resolve
