### ISSUE TITLE
[Chore] Update Form Controls

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#361]
### What general chore or task would you like to see performed?
Please make the follow changes to the form controls. These are general changes that need to be made to all the form controls and states, not just inputs.

**For Reference:**
Form Controls: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5cd3f2bd5fbc24c9a64bc2ec
Form States: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d4d8dd584c33a157acf87a0

**Form Control Changes:**
- [x] Placeholder weight should be Light - currently Regular
- [x] Placeholder padding left/right should be .5rem - currently .75rem
- [x] Placeholder padding top/bottom should be .55rem - currently .5rem
- [x] Placeholder should be 14px - currently 16px
- [x] Control border color should be lighten(#b1b1b1, 13.5%);
- [x] Line height needs to be removed
- [ ] Padding on each side of the outside of the input should be .5rem - currently 1rem
- [ ] Padding on bottom of outside of the input should be 1rem - currently is also 2rem

**Form State Changes:**
- [x] When a user hovers over a form item, it should have the following box shadow: 0px,0px,0px,3px rgba(211,211,211,0.25)*
- [x] When a user selects a form item, it should have the following box shadow: 0px,0px,0px,3px rgba(0,131,143,0.25)*
- [x] When a user selects a form item that has an error, it should have the following box shadow: Box Shadow: 0px,0px,0px,3px rgba(219,57,57,0.25)*
- [x] Disabled inputs should not have a lock at the end of them

*All these box shadows are the same and match the box shadows that will go on any form components (buttons, radios, switch, checkboxes, etc). This box shadow SHOULD replace the one currently being used on form controls because that box shadow isn't used anywhere but here.

**Comment by grahamhency** [comment]
Hey @kpmurphh, got some questions/comments about this.

1. The input heights should be determined by their content.
> Input height should be 36px

2. I have concerns over making these placeholder changes. I think the padding will seem weird in use because it will appear as though when you start typing the text would shift. 
> Placeholder weight should be Light - currently Regular
> Placeholder padding left/right is 8px - currently 12px
> Placeholder should be 14px - currently 16px

3. I would encourage us to make use of any of the current box shadows we have instead of adding more. Could these be changed to one of those?
> When a user hovers over a form item, it should have the following box shadow: 0px,0px,0px,3px rgba(211,211,211,0.25)
> When a user selects a form item, it should have the following box shadow: 0px,0px,0px,3px rgba(0,131,143,0.25)

4. Why not, it looks cool? imo
> Disabled inputs should not have a lock at the end of them

5. This is browser specific and an image:
> The disabled input “not interested” hover should be Horizon

**Comment by kpmurphh** [comment]
1. Okay

2. I should have clarified. These are changes for the entire input text. These changes should apply to both the placeholder and the text the user enters so it doesn't shift or change when the user begins adding information. 

3. This box shadow treatment is being used on forms and buttons so there's more than just this use for it. If the box shadow being used on form hover/select/error select isn't being used anywhere else, then it can be replaced by this one. If it is, please add this one.

4. We discussed and we find the lock to be confusing and unnecessary. There's already enough indication that the input is disabled without the lock. We'd prefer the disabled input to just have the not interested hover. If you have any questions feel free to ask Jason.

5. Okay no problem.

**Comment by grahamhency** [comment]
This box-shadow for hover is really hard to see:
![Screen Shot 2020-02-05 at 11 45 22 AM](https://user-images.githubusercontent.com/11966331/73862760-055d5980-480d-11ea-8963-7cbdd1c54ca8.png)

What do you think about bumping the opacity on the color to 50%?
![Screen Shot 2020-02-05 at 11 46 19 AM](https://user-images.githubusercontent.com/11966331/73862876-2d4cbd00-480d-11ea-8e7f-9f4b2042cf4a.png)

**Comment by grahamhency** [comment]
These two items are coming from the grid, not the inputs. If we want to change those, that's a different issue and will have a much bigger impact.
> Padding on each side of the outside of the input should be .5rem - currently 1rem
 Padding on bottom of outside of the input should be 1rem - currently is also 2rem

**Comment by kpmurphh** [comment]
> This box-shadow for hover is really hard to see:
> ![Screen Shot 2020-02-05 at 11 45 22 AM](https://user-images.githubusercontent.com/11966331/73862760-055d5980-480d-11ea-8963-7cbdd1c54ca8.png)
> 
> What do you think about bumping the opacity on the color to 50%?
> ![Screen Shot 2020-02-05 at 11 46 19 AM](https://user-images.githubusercontent.com/11966331/73862876-2d4cbd00-480d-11ea-8e7f-9f4b2042cf4a.png)

That's fine with me.

**Comment by Fagiolia1** [comment]
> These two items are coming from the grid, not the inputs. If we want to change those, that's a different issue and will have a much bigger impact.
> 
> > Padding on each side of the outside of the input should be .5rem - currently 1rem
> > Padding on bottom of outside of the input should be 1rem - currently is also 2rem

Since this needs to be fixed for the form inputs, what would be the impact across the board and how can it be addressed?

**Comment by cosmicdust73** [comment]
> > These two items are coming from the grid, not the inputs. If we want to change those, that's a different issue and will have a much bigger impact.
> > > Padding on each side of the outside of the input should be .5rem - currently 1rem
> > > Padding on bottom of outside of the input should be 1rem - currently is also 2rem
> 
> Since this needs to be fixed for the form inputs, what would be the impact across the board and how can it be addressed?

We discussed this issue back in July when the team was out in Indy. The Telecom Ordering team does not have this issue today because they are using Bootstrap's grid, which allows for adjustment of form label and input spacing independently from the rest of the grid layout. They achieve this using inside divs/classes that are scoped to the form itself. (i.e. 'form_group') 

Since this has to get fixed in goponents, can we not explore enhancing the grid in a similar fashion... or scoping the spacing change to forms only?

**Comment by grahamhency** [comment]
@cosmicdust73, @kpmurphh, @Fagiolia1 I am not saying we can't do this, just that the change is outside of the scope of this issue because that change is not specific to forms.

I would request a second issue be opened around adjusting the grid gutter spacing across the board. That task will be much more in depth because we will need to replace anywhere the `column-gutter` variables are used outside of the form, which is extensive.

**Comment by grahamhency** [comment]
Closed with #459
