### ISSUE TITLE
[Feature] Grid Padding for Forms

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#455]
### What general chore or task would you like to see performed?
Form inputs currently are wrapped within the go-column class which has:
```
padding-bottom: 2rem;
padding-left: 1rem;
padding-right: 1rem;
```

Can these inputs instead be:
```
padding-bottom: 1rem;
padding-left: .5rem;
padding-right: .5rem;
```

**Comment by grahamhency** [comment]
This issue was spurred from the conversation in issue #361

**Comment by eligolding** [comment]
So just to clarify, this issue is not really about the padding on the _inputs_, rather that the grid system should have tighter gutters when laying out forms.

There are two ways we can go about this:
1. A set of `go-container-*` classes that define the gutter size for that container.
    * Pros: relatively easy to do in CSS
    * Cons: the user needs to remember to use these classes when laying out forms

2. A `go-form` component that manages laying out the inputs.
    - Pros: cleaner code when building forms, less room for error
    - Cons: javascript heavy.

**Comment by grahamhency** [comment]
Thanks for clarifying @eligolding, I updated the title to reflect better what this is.
