### ISSUE TITLE
[Chore] Remove padding-bottom from card_header class

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#468]
### What general chore or task would you like to see performed?
Currently the card_header class has a padding-bottom of 1rem. This, along with the margin-bottom applied to all header classes is creating a 40px bottom gutter to all header elements.

**Comment by eligolding** [comment]
Honestly I would quicker remove the `margin-bottom` from the `go-heading` classes, reverting it back to the `.5rem` that it used to be. Since `h` tags are almost always nested within either a column or a heading container such as this card heading, I find myself pretty much always adding the `go-heading--no-margin` class to get the correct padding.
