### ISSUE TITLE
go-nav-item with isExternalLink set to true always opens new browser tab.

### ISSUE THREAD

**Issue by sudheepdivakargithub** [mobi/goponents#616]
**Describe the bug**
go-nav-item with isExternalLink set to true, and a name set to externalLinkTarget always opens a new browser tab.

**To Reproduce**

**Expected behavior**
go-nav-item with isExternalLink set to true, and a name set to externalLinkTarget should refresh the already opened tab.

**Comment by grahamhency** [comment]
@sudheepdivakargithub can you provide a code example here?

**Comment by venkatesh1982** [comment]
Hello. Example below.
We set the nav-item with the below properties.
{
              routeTitle: "Workflow",
              route: this.wfmodelerRedirectUrl,
              routeIcon: "device_hub",
              description: "Workflow",
              **isExternalLink: true,
              externalLinkTarget: "WFModeler",**
 }

Element rendered as below.
```
<a _ngcontent-ogw-c18="" class="go-nav-item__link ng-star-inserted" rel="noreferrer" href="http://localhost:9000/yamlconfig/redirectwfmodeler" target="WFModeler">
...
</a>
```

The expectation is, since we have specified the target (externalLinkTarget), any number of clicks on the menu item should open the content in the same tab if opened or else one new one if none exists.
But, actual is it opens the URL always in a new tab.

We tried to remove the property `rel="noreferrer"` , it then works as expected.

**Comment by grahamhency** [comment]
The `externalLinkTarget` property is the same as the `target` attribute on an `<a>` tag. Thus it can only be one of four options: 

`externalLinkTarget?: '_self' | '_blank' | '_parent' | '_top';`

By default we set it to `_blank`. In the example you provided, you're setting `externalLinkTarget: "WFModeler"` which is not a valid option.

To have this nav item open in the same tab, you'll need to set `externalLinkTarget:  '_self'`.

For more information, you can check the "menuItems" section on the documentation for the side nav: https://tangoe.design/ui-kit/layout/side-nav

**Comment by venkatesh1982** [comment]
May be we are not clear.  

Lets say we are in main app which is opened in tab 1. we click a menu item and this is the external URL which has to opened in a new tab, say tab 2. If the user goes back to tab 1 and then again clicks on the same menu item, currently, a new tab is again opened (tab 3) and so on. 

What the expectation is that since tab 2 is already opened (tab not closed), clicking on the same menu item again from main app, should not open a new tab (tab 3), but just reload tab 2. 

In general, for <a> tag this can be achieved by specifying a custom target name. So any number of clicks to the same link will not keep opening new tabs, but will reload  (reuse the target) if already opened.

May be we can have quick call if we need to discuss this further.
