### ISSUE TITLE
[Chore] Hide dropdown arrow on go-select

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#636]
### What general chore or task would you like to see performed?
When there are no items in a typeahead select, the dropdown arrow should be hidden.

Note: The dropdown arrow should only be hidden when `[typeahead]="true"` and there are no items

**Comment by Ashygoyal** [comment]
@grahamhency : just to understand more on the requirement,
`The dropdown arrow should only be hidden when [typeahead]="true" and there are no items`

_no items_ : does it imply on page load or for a particular search query while using typahead?
for example, 
Case 1: the list of items might contain 
`['apple', 'banana', 'grapes']`, but if you type 'lemon', the list would show no results?
Case 2: the list is empty on page load

Because this would help me decide whether to put check on the _items_ or on `control.valueChanges`
Please correct me If I am wrong.

**Comment by grahamhency** [comment]
@Ashygoyal I believe it would be if on page load there are no items in the array.
