### ISSUE TITLE
[Chore] Change App Drawer Read Only Text

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#664]
### What general chore or task would you like to see performed?
Please change the following in the app drawer read only text:

- Instead of reading "Switch To..." the read only text should read "Launch..."
- **Can we take the hover and arrow cursor off the Read Only text component? It currently looks like a link that is broken and it should not.**

**Comment by grahamhency** [comment]
> When you say 'Read Only text component', do you mean the header of the app drawer, the section that contains the text 'Launch'

@Ashygoyal this statement is correct and yes, the second request should already have been taken care of with #651 

I would like to add an additional request to this because it is directly related. Can we make this static text a binding in the component that defaults to "Launch..."? This way it would allow each app to pass in translated text depending on locale.

**Comment by Ashygoyal** [comment]
> > When you say 'Read Only text component', do you mean the header of the app drawer, the section that contains the text 'Launch'
> 
> @Ashygoyal this statement is correct and yes, the second request should already have been taken care of with #651
> 
> I would like to add an additional request to this because it is directly related. Can we make this static text a binding in the component that defaults to "Launch..."? This way it would allow each app to pass in translated text depending on locale.

@grahamhency : Done and Dusted !!
