### ISSUE TITLE
[Chore] Off-Canvas Component Changes

### ISSUE THREAD

**Issue by kpmurphh** [mobi/goponents#682]
### What general chore or task would you like to see performed?
There are three changes that are required to match DSM specs in the off-canvas.

1. Please make the width of the off-canvas 350px.

2. Please make the following changes to the off-canvas "dark" components:
- The background color of each input should be #313536 (currently #202626)
- The border color should be #202626 (currently #D3D3D3)

3. The button that triggers the actions in the off-canvas should be a full-width button that is located at the bottom of the off-canvas. Please refer to the DSM documentation for images: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-ds/folder/components/5d6ecba0bbf330b5e308562c

**Comment by jaredami** [comment]
Hey @kpmurphh, I just wanted to clarify some things regarding point #2. 

Are those style changes to form inputs supposed to apply to *all* dark form inputs, or just the inputs in the off-canvas? I would think it would be the former, since otherwise that would create an odd inconsistency between the off-canvas and other dark forms, but you only mentioned it applying within the off-canvas, so I wanted to check.
 
Also, just to clarify, is this how the inputs are supposed to look?

<img width="351" alt="Screen Shot 2020-10-23 at 10 37 28 AM" src="https://user-images.githubusercontent.com/23343417/97185376-584db700-1776-11eb-8b3c-741a9dc08425.png">

**Comment by grahamhency** [comment]
@jaredami yeah I think this is intended for _all_ dark forms. I don't believe we use dark forms anywhere else other than the off-canvas for now so that's probably why it's worded that way.

We will probably want to consider every form element we have for this..
