### ISSUE TITLE
[Feature] Dark Themed Toasts

### ISSUE THREAD

**Issue by grahamhency** [mobi/goponents#737]
### What is the feature that you would like to propose?
The ability to style a `go-toast` for a dark theme.

_**Example of issue with light theme:**_
![Screen Shot 2021-01-27 at 12 19 13 PM](https://user-images.githubusercontent.com/11966331/106028389-e0a36700-6099-11eb-9a7a-f25f97d16963.png)

### Describe the solution you'd like
I'm requesting the addition of a new binding on a `go-toast` for `theme` with options for `light` (which would be default) and `dark`.

**Comment by grahamhency** [comment]
@mobi/tangoe-ux-ui if you can, ideally we'd prefer some documentation around what the specs should be for this prior to building it. Can one of you take a look at this and provide us with those docs please? 😄

**Comment by kpmurphh** [comment]
> @mobi/tangoe-ux-ui if you can, ideally we'd prefer some documentation around what the specs should be for this prior to building it. Can one of you take a look at this and provide us with those docs please? 😄

Sure! I'll take care of this.

**Comment by kpmurphh** [comment]
@grahamhency I added documentation to the toasts page on dark theme toasts: https://tangoe.invisionapp.com/dsm/tangoe/tangoe-dsm/nav/5fa7cb5d8c0120001835592d/asset/5ee27230722fa9980fca7fc1

I'm tagging @cosmicdust73 as a reminder because he had some questions regarding this use case but that is for another discussion and github issue 😄
